require("config/options")
require("config/keymaps")
require("config.diagnostics")
require("config.autocmds")
require("config.lsp")
require("config.pairs")
-- require("config.tabline")
require("config.statusline")
-- require("config.ui2")
